### ISSUE TITLE
Bi-directional bridge?

### ISSUE THREAD

**Issue by maxlinux2000** [radian-software/unzuckify#1]
Your work, is very interesting

I wonder if it could eventually become a two-way bridge.

There is a group of users very interested in a bridge between facebook and email.
These users use the Deltachat App and with a two-way bridge they could communicate with others on Facebook.

Cheers
MaX

**Comment by raxod502** [comment]
No comment. Of course, the work is open-source, so anybody is free to build on the foundation as they wish. But I personally have no interest in further development on Facebook or Messenger, since the express purpose of this project was to allow me to completely remove them from my life.

Delta Chat looks interesting. I've seen good things from Matrix as well.

**Comment by raxod502** [comment]
Closing as out of scope for this particular project, although I would have no objection to a fork building on this to be a more full-featured client.
